analyzers:
  crbot:
    type: diagnostic_aggregator/GenericAnalyzer
    path: crbot
    # find_and_remove_prefix: 'pin'
    expected: ['battery']
    # contains: 'nAAA'
    # startswith: 'Battery'
    timeout: 5.0